### ISSUE TITLE
`--extra-spliced` and `--extra-unspliced` options of `make-splici` only add two t2g columns, resulting in `alevin-fry quant` panic

### ISSUE THREAD

**Issue by jashephe** [COMBINE-lab/pyroe#1]
The options ` --extra-spliced` and `--extra-unspliced` of `pyroe make-splici` only add two columns to the T2G map file. Here's one of the relevant lines of code:

https://github.com/COMBINE-lab/pyroe/blob/dc2c8df8fd2577ff3b35f5d15aa69270a201b05f/src/pyroe/make_splici_txome.py#L362

However, all of the other lines written to the T2G map file have three columns. When you try to use the resulting T2G map file as input to `alevin-fry quant`, it results in the fairly cryptic "`could not quantify rad file.`", triggered by one of the panics in the vicinity of [this line](https://github.com/COMBINE-lab/alevin-fry/blob/a120443cd8ea90fc7f348c3aa620a98fda7e00e2/src/main.rs#L417). By manually modifying the T2G map file to have a third column, the `alevin-fry quant` panic was resolved.

**Comment by rob-p** [comment]
Cc @DongzeHE

**Comment by rob-p** [comment]
Hi @jashephe,

  Thanks for reporting this.  It seems that we still have some rough edges for pyroe to polish before it reaches total parity with [`roe`](https://github.com/COMBINE-lab/roe), though we're committed to this goal, since there are many places where it's just easier to use python.  Anyway, I've just fixed this issue and tagged and pushed a new version (v0.3.1 — only bumping the patch since this is a bug fix) to pypi.  Please let us know if this works for you.

Best,
Rob

**Comment by rob-p** [comment]
@jashephe,

  I'll also note that @DongzeHE also fixed some small (but important bugs) and we just pushed a new version (0.4.0) to pypi and it should be on bioconda soon.  This one reaches nucleotide parity with the R `roe` package on some real transcriptomes we've tested and we recommend you upgrade to this version when you have a chance.

Thanks!
Rob
