### ISSUE TITLE
Bug in id-to-name

### ISSUE THREAD

**Issue by zedongL** [COMBINE-lab/pyroe#39]
When I tried `pyroe id-to-name --format .GTF  gencode.vM25.annotation.gtf ./test_pyroe.tsv` 
I got `ERROR:root:Format must be either "gtf" or "gff3", but .gtf was provided.`.
Then I tried `pyroe id-to-name --format gtf  gencode.vM25.annotation.gtf.gz ./test_pyroe.tsv`
I got 
Traceback (most recent call last):
  File "/bin/pyroe", line 296, in <module>
    id_to_name(args)
  File "/site-packages/pyroe/id_to_name.py", line 38, in id_to_name
    annot_reader = format_map[fmt]
                   ~~~~~~~~~~^^^^^
KeyError: 'gtf'

I think the inconsistency in the `format_map` and `if fmt not in ["gtf", "gff3"]:` at line 33 cause this problem.

**Comment by rob-p** [comment]
Hi @zedongL,

  Thanks for reporting this.  The issue has to deal with how the suffix is parsed (in particular when the input contains multiple "suffixes").  I have pushed a fix to the develop branch and will tag and release a new version when the testing finishes.  In the meantime, you may be able to get the command to run with your file by changing the filename.  Perhaps try renaming `gencode.vM25.annotation.gtf` to `gencode_vM25_annotation.gtf`, and leave off the explicit format.  So do:

```
pyroe id-to-name gencode_vM25_annotation.gtf ./test_pyroe.tsv
```

Otherwise, the upcoming v0.9.3 should handle everything properly without jumping through these hoops.

Best,
Rob

**Comment by rob-p** [comment]
This is now released and merged into bioconda as well.
