### ISSUE TITLE
Duplicate entries for spliceu index

### ISSUE THREAD

**Issue by davidaknowles** [COMBINE-lab/pyroe#41]
I'm not sure if I should be asking this here or on the `alevin fry` repo or here but anyway: I'm building a `spliceu` index and then using it for aligning a SPLiT-seq single nuclei (mouse) dataset. I'm trying to understand how duplicate entries from the GTF are handled. Naturally enough, for all single exon genes the unspliced pre-mRNA and the (presumably single) transcript are "duplicates", and these are deduped from `spliceu.fa` if I use the `--dedup-seqs` option to pyroe. However, they are not removed from e.g. `spliceu_t2g.tsv` or the resulting quantification after running `quant`, e.g. the duplicates are in the dumped equivalence classes (what I actually want to use) as well as `quants_mat_cols.txt`. This seems odd to me: wouldn't you want to avoid having duplicated features to align to and quantify (since they are indistinguishable anyway)? 
Happy 4th :)

**Comment by rob-p** [comment]
Hi @davidaknowles,

  Thanks for reporting this.  I think it's fine to report it here, though with our movement from `pyroe` to `roers`, we'll want to make sure that we include any changes there as well (cc @DongzeHE).

  I agree that it seems somewhat inconsistent to remove the sequence from the generated fasta but to leave the labels in the `spliceu_t2g.tsv` (which therefore propagate to the `quants_mat_cols.txt` file).  I guess there is a legitimate question of how one should handle a cases such as this.  I see 2 options that would be "consistent":

  1. Remove all but one of the sequence identical targets, but then generate _another file_ that provides the mapping from representative to discarded sequence-identical target.  This is essentially what `salmon` does with the file `duplicate_clusters.tsv`.  The benefit of this approach is that the fasta and t2g file are entirely consistent, but at the same time the relevant information is recorded if the user wants to use it downstream.  With some extra cycles, we could even develop a function that considers this mapping when loading the matrix into R/Python and "re-populates" the identical targets ... though how to do that and what the policy should be is still a bit of an open question.
  2. Remove all but one of the identical sequence targets, remove the corresponding entry from the t2g file, and don't produce any extra information recording the duplication status.  This keeps things as simple as possible, but certainly loses some information.

  There may be other possibilities as well, so I'm happy to hear if you have any thoughts on this.  Also, I hope you had a great 4th :).

Best,
Rob

**Comment by DongzeHE** [comment]
Hi @davidaknowles ,

Thanks for bringing this up. I think this is really a question because in pyroe, we do deduplicate identical sequences, but when doing it, we sort the transcript names that share the same sequence and take the first one as the representative name. This behavior may sometimes prefer to keep unspliced transcript names. For example, when sorting ENST an ENSG, ENSG will always win. In your case, I would suggest you run pyroe without the `dedup-seq` flag and filter the sequences by yourself because, currently, pyroe does not ensure that the spliced transcripts are always kept rather than the unspliced transcripts. This will be easy to do, you can slightly modify the function we defined [here](https://github.com/COMBINE-lab/pyroe/blob/7e69996a87f180e3b90c2c8eaa8206511b52f192/src/pyroe/make_txome.py#L54), and you replace the logic in line 91-93 with any logic you want to use.

@rob-p We might want to rewrite the dedup_seq function because if we have a single-exon transcript, we might want to keep both sequences so that reads map to this transcript will also map to its unspliced counterpart so that they can be classified as the ambiguous state, what do you think?

Best,
Dongze

**Comment by davidaknowles** [comment]
Thanks both. For the specific case of single exon genes, I think these should be deduped: there is no distinction between spliced and unspliced (since the mature RNA = pre-mRNA!) so there is no real ambiguity. Then it's just a matter of semantics whether you label with the gene or transcript name (the only tricky part is what label you give in _3col.tsv). 
For deduping other sequences would it be problematic at all to label these with the concatenation of the sequence names? That would avoid creating an additional file. 
And just so I understand: index building and alignment will only look at the fasta (but not t2g.tsv), but `quant` will look at t2g.tsv (or t2g_col.tsv)?

**Comment by rob-p** [comment]
Hi @davidaknowles,

> And just so I understand: index building and alignment will only look at the fasta (but not t2g.tsv), but quant will look at t2g.tsv (or t2g_col.tsv)?

Right; so I discussed this at some length with Dongze to understand everything that's happening.  Let me explain as clearly as possible:

 * First, yes, indexing and alignment will consider *only* the fasta file, not what is in the `t2g.tsv` or `t2g_3col.tsv`.  What is in the fasta file is what gets indexed and what gets aligned against.

 * The reason for having the distinct entries, even for e.g. single-exon genes, in the `t2g_3col.tsv` and hence the count matrix is a bit more involved.  Basically, this is expected even if the sequences are deduplicated.  The reason for this is that during quantification, `alevin-fry` considers it an invariant that for every gene, it is possible to allocate counts as spliced, unspliced, or ambiguous.  Thus, even if a count will never be assigned to the unspliced version of a gene (because e.g. it has been tagged as a duplicate with the spliced version), there will still be a _label_ for the unspliced version of that gene ... it will just always obtain a 0 count.  This is actually an important distinction, and an underlying invariant that is important to some of the modeling in `alevin-fry`.  So I think we want to say that, even when we adopt a deterministic policy, like saying that counts should always contribute to the "spliced" slice for a single-exon gene, there will still be a slot in the count matrix for the "unspliced" version of this gene, it will just always have count 0.  Likewise, this relates to the fact that the USA mode matrix is always of size `3G x C` where `G` is the total number of genes.

 * So `pyroe` (though not yet `roers`) already outputs a `duplicate_entries.tsv` file when you pass the `--dedup-seqs` option.  This goes in the same output directory as the `t2g` files and the fasta files.  It is a simple 2 column file listing the Retained and Deduplicated sequence pairs.  I think it is useful to produce this file, and it could be considered in downstream analysis where relevant to help make general sense of the duplicate sequences.  @DongzeHE can discuss the possibility of also renaming deduplicated sequences, though this might also run into the problem of generating completely novel names that won't map within other resources (e.g. enrichment or functional databases etc.).

In general, I think the action items here are to:

  1) Explain clearly what the effect of deduplicating sequences is on both the fasta file (what will be mapped against) and the annotation file (the `t2g`s) so that is clear to users
 
  2) Implement and document a *policy* on duplicate retaining preferences — i.e. when you have single exon genes, which "version" is kept and how that should be dealt with in the index.  This is actually a bit more complex that it may initially seem, because it depends a bit on the semantics of what one views as spliced / unspliced or mature / nascent.  For example, in the `splici` reference, there are no introns in a single-exon gene, so it makes sense for it to only ever be considered as a "spliced" molecule.  However, for the `spliceu` reference, perhaps it should be considered ambiguous (i.e. deduplication should be done separately within the spliced and unspliced sequences).  This is more a matter of terminology and interpretation and worth discussing.

 3) Develop and provide some relevant functions (in python & R) to do processing & munging of data where sequences have been deduplicated and the duplicates should be accounted for in certain ways.  This is really several different behaviors rather than one.  In many cases, simply ignoring (allowing a 0 count for) the duplicates is sufficient.  However, it would be nice to mark in the count matrix when a feature is a "duplicate" and hence likely uniformly 0 for that reason.  Likewise, it would also be nice to have the functionality to "splat" duplicates over equivalence class labels.  That is, when an equivalence class label contains the retained target, we can augment the class to also include the targets that have been discarded, since the same reads would have mapped to them as well.  Finally, it _may_ be useful to have the functionality to redistribute counts from retained to discarded sequences (e.g. to move counts from unspliced to spliced duplicates, or to re-balance counts uniformly over all duplicate sequences).  This still needs a bit more thought, but I think a small library of functions to perform such operations could be useful.

Best,
Rob

**Comment by davidaknowles** [comment]
Thanks, this all sounds reasonable. For now I'm going to take `duplicate_entries.tsv` and use it to remove entries from `t2g.tsv` etc before quantification. I'm primarily interested in looking at alternative splicing variation so the single exon genes are only of interest to me as places that multimapping reads could get (partially) assigned to.

**Comment by davidaknowles** [comment]
Hmm so with my deduped `t2g.tsv` I'm getting an error when I go to run `alevin-fry quant`: 
```
2023-07-06 17:50:54 INFO quantifying from uncompressed, collated RAD file File { fd: 4, path: "/gpfs/commons/groups/knowles_lab/data/parse/original_SPLITseq_GSE110823/salmon_spliceu/out_permit_knee/map.collated.rad", read: true, write: false }
2023-07-06 17:50:55 INFO paired : false, ref_count : 116,918, num_chunks : 192,395
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `96955`,
 right: `116918`: The tg-map must contain a gene mapping for all transcripts in the header', src/utils.rs:234:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I think the rad file knows there should be more entries in `t2g.tsv`: maybe I need to rerun `collate`? 
Edit: rerunning collate doesn't change anything.

**Comment by rob-p** [comment]
Hi @davidaknowles,

  So the constraint here is that all of the transcripts that appear in the header of the RAD file should have some mapping to a gene in the `t2g` map.  You can see what targets are listed in the RAD file using the `view` sub-command.  That is the minimal set of targets that must appear in the `t2g` file.

  If you want to share the RAD file, your t2g mapping, and your duplicate_entries file, @DongzeHE and I are happy to take a look.

Best,
Rob

**Comment by davidaknowles** [comment]
Thanks. I have a solution that works for me now by having a custom `t2g` that maps duplicate transcripts to a single reference transcript (I want transcript level quantification and more specifically EC data). 
The thing I'm still slightly confused about is how the RAD file ended up including the duplicate transcripts since they are not in the (deduped) fasta.

**Comment by davidaknowles** [comment]
Is there a way to have `view` show me only the targets and not the alignments?

**Comment by rob-p** [comment]
You can pass the `-H` flag, which should print the header. There's not currently an option to print *only* the header (though we should add that...).  The easiest thing to do would probably be to just pipe the output of `view` to head and cut the number of lines you want.  All of the read records start with `ID`, so you could just filter out the lines that start with `ID` to retain only the header lines.

**Comment by rob-p** [comment]
Hi @davidaknowles,

  Were you ever able to resolve this? Should I close the issue, or is there something lingering that @DongzeHE and I should look into?

Thanks!
Rob

**Comment by davidaknowles** [comment]
Fine to close it for now.
